# Generated by Django 6.1.1 on 2026-09-29 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetriaESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='192.168.1.145', max_length=50)),
                ('rssi', models.IntegerField(default=-58)),
                ('online', models.BooleanField(default=True)),
                ('ultimo_uid_leido', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_limite_retardo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('uidRfid', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fechaAlta', models.DateField(auto_now_add=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.carrera')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accesos.rol')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.semestre')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('autorizado_por', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.usuariorfid')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_leido', models.CharField(max_length=50)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('puerta', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('a_tiempo', 'A tiempo'), ('retardo', 'Retardo'), ('denegado', 'Denegado')], max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.usuariorfid')),
            ],
        ),
    ]
