# Generated by Django 6.1.1 on 2026-10-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_seguridadadministrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguridadadministrador',
            old_name='is_tottp_enabled',
            new_name='is_totp_enabled',
        ),
    ]
